//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;


    public partial class Populer_Icerikler
    {
        public int id { get; set; }
        [DisplayName("Popüler İçerik Adı")]

        public string pop_icerik_adi { get; set; }
        [DisplayName("Popüler İçerik Fotoğrafı")]

        public string pop_icerik_img { get; set; }
        [DisplayName("Popüler İçerik İndirme Linki")]

        public string pop_icerik_link { get; set; }
    }
}
