//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;


    public partial class Urunler
    {
        public int id { get; set; }
        [DisplayName("Ürün Adı")]

        public string urun_ad { get; set; }
        public Nullable<int> altKategori_id { get; set; }
        [DisplayName("Ürün Fotoğrafı")]

        public string urun_img { get; set; }
        [DisplayName("Ürün İndirme Linki")]

        public string indirme_linki { get; set; }

        public virtual Alt_Kategoriler Alt_Kategoriler { get; set; }
    }
}
