//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class finalprojectEntities1 : DbContext
    {
        public finalprojectEntities1()
            : base("name=finalprojectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Uye_giris> Uye_giris { get; set; }
        public virtual DbSet<Alt_Kategoriler> Alt_Kategoriler { get; set; }
        public virtual DbSet<Cihazlar> Cihazlar { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<Populer_Icerikler> Populer_Icerikler { get; set; }
    }
}
